### ISSUE TITLE
Firestore update command does not update the document

### ISSUE THREAD

**Issue by bettinatop22** [prescottprue/cypress-firebase#10]
Hello, 

when I try to update a document in firestore it's not updated and an error occurs with the following message: 

> update() requires either a single javascript object or an alternating list of field/value pairs

This is probably due to the fact that the data for update is not passed in the corresponding command:
https://github.com/prescottprue/cypress-firebase/blob/d7a84394181866d19b845ed3efa1051e0465e02d/src/buildFirestoreCommand.js#L48

I tested it locally by passing the fixturePath as a third argument and it seems to be working as expected. 

Let me know what you think. I'd happily submit a fix for this.

Thanks,
Bettina

**Comment by prescottprue** [comment]
Fix released in [`v0.1.1` release](https://github.com/prescottprue/cypress-firebase/releases/tag/v0.1.1), thanks for reporting and providing the PR.
