### ISSUE TITLE
publish-npm failing Error: Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by eldu** [prescottprue/cypress-firebase#1023]
**Describe the bug**

the publish-npm workfollow is failing

```
Error: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/index.js from /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/src/index.js not supported.
```

**To Reproduce**

1. Go to see the latest runs on main. Here is one of them https://github.com/prescottprue/cypress-firebase/actions/runs/5548318257/jobs/10131150696

**Expected behavior/code**
It should pass

**Possible Solution**

Adjust import and require?

**Additional Context/Screenshots**

**Comment by prescottprue** [comment]
Fixed in https://github.com/prescottprue/cypress-firebase/releases/tag/v3.0.2 - thanks for calling out
