### ISSUE TITLE
"data.projectId must be projectId format" CircleCI config error

### ISSUE THREAD

**Issue by asaldivar** [prescottprue/cypress-firebase#109]
Thank you @prescottprue for such a useful package. A few questions regarding the configuration of `cypress-firebase` with CircleCI. I referenced issue #23 which helped me get to where I am now. 

As a note, I have am using your package perfectly  in my local environment. The command I'm using is essentially, `yarn run build:testConfig && cypress run` where `build:testConfig` is `cypress-firebase createTestEnvFile`

First, I'm hoping you can clarify that these logs in CircleCI prove that I my `SERVICE_ACCOUNT` environment variable is properly accessible:

```
$ cypress-firebase createTestEnvFile
ℹ Service account does not exist at path: "serviceAccount.json" falling back to environment variables...
ℹ Generating custom auth token for Firebase project with projectId: auth-core-api
✔ Custom token generated successfully, writing to cypress.env.json
✔ cypress.env.json updated successfully
```

It looks like `cypress-firebase` was able to create a an auth token with the `SERVICE_ACCOUNT` env variable. Is that correct?

But then immediately after I get the following error:

```
[03:34:49]  Verifying Cypress can run /root/.cache/Cypress/4.1.0/Cypress [started]
[03:34:51]  Verifying Cypress can run /root/.cache/Cypress/4.1.0/Cypress [completed]

Opening Cypress...
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
ℹ Service account does not exist at path: "serviceAccount.json" falling back to environment variables...
Initialized with Service Account for project "auth-core-api"
Recording this run failed because the request was invalid.

Request should follow postRunRequest@2.2.0 schema

Errors:

[
  "data.projectId must be projectId format"
]
```

I'm not sure where to go from here with `data.projectId` and `postRunRequest`. For further context, I'm using version `^0.11.0` of `cypress-firebase`. Thanks in advance for any guidance.

**Comment by asaldivar** [comment]
This was my bad. This was actually a `cypress` issue I caused by not setting the right projectId value in my CircleCI environment variables.

**Comment by prescottprue** [comment]
Thanks for reaching out - something to note is that the v1 pre-release versions (available on the `next` tag) no longer contains `createTestEnvFile` and actually generates required configs dynamically
