### ISSUE TITLE
README - unclear meaning of "sub-bullets" for Auth sec. 7

### ISSUE THREAD

**Issue by gregfenton** [prescottprue/cypress-firebase#113]
- Usage
   - Setup
      - Auth
There are 2 numbered points that come after (or sub-bullets to?) bullet #7 in the Auth section.

> 1. Make sure to set CYPRESS_TEST_UID environment variable in your CI settings if you are running tests in CI
> 1. Call cy.login() with the before or beforeEach sections of your tests

Not clear how these relate to the Setup, or if these are starting to talk more about usage once the system is up?  Maybe these could/should be moved to a separate section away from "Setup", like maybe a separate "Considerations for CI" section?

A request: at the end of the Setup section have a step that "confirms things are working" ?  Even if that was a simple Recipe that requires additional tools (e.g. a default Cypress setup, a simple example script), it would be a huge help in getting people started.

For newbies (me!), I fear overloading the section meant to just "get things up and started".  I feel like I'm being led into deeper areas before I know that the basics are in place.  (And maybe this is just me not having captured enough knowledge of all the moving parts yet...)

**Comment by prescottprue** [comment]
Thanks a bunch for bringing this up, I totally agree! Fixed in a push just now
