### ISSUE TITLE
README: test:emulators script dependencies

### ISSUE THREAD

**Issue by gregfenton** [prescottprue/cypress-firebase#115]
On my (new MacOS) system that (I'm trying to leave as clean as reasonable and possible), I get:

`$ npm run test:emulate`

`> auth-and-profile@0.1.0 test:emulate /Users/greg/work/react-firebase-auth-and-profile`
`> cross-env FIREBASE_DATABASE_EMULATOR_HOST="localhost:$(cat firebase.json | jq`
`.emulators.database.port)" FIRESTORE_EMULATOR_HOST="localhost:$(cat firebase.json | jq`
`.emulators.firestore.port)" yarn test:open`

`sh: jq: command not found`

The test:emulate script depends on both `jq` and `yarn`. 

jq I get and can live with (`brew install jq`), but just about everything else on this project uses npm rather than yarn.

Didn't want to submit a PR for this change without a discussion :)

**Comment by prescottprue** [comment]
Yeah this was copied over from another project, so we can go back to npm. This project uses yarn currently (hence the yarn.lock), but open to the idea of leaving all of the scripts as npm so it isn't required.

Out of curiosity are you not installing with yarn? You get a warning in npm that there is a yarn.lock right?

**Comment by gregfenton** [comment]
I am installing with npm.  I didn't notice any warnings/errors from npm.  I just uninstalled and installed again with npm and no errors that I can see:

```
$ npm install cypress-firebase 
 + cypress-firebase@1.0.0
 added 1 package from 1 contributor and audited 932071 packages in 9.993s
 
 66 packages are looking for funding
   run `npm fund` for details
 
 found 5 low severity vulnerabilities
   run `npm audit fix` to fix them, or `npm audit` for details
$
```

Not sure if you expected otherwise?

**Comment by prescottprue** [comment]
@gregfenton I meant within this repo itself - I had assumed you were running the scripts within a forked version of this repo since you were referencing the npm scripts.

For installing in another project it should matter whether you use npm or yarn since you presumably won't be running any npm scripts within a dependency, unless I am misunderstanding?

**Comment by gregfenton** [comment]
I was using the `emulators`, `test:open` and `test:emulate` config/scripts as a template for my project (create-react-app + firebase + cypress.io) in terms of starting up the emulators and running tests.

Guess I am getting too far ahead of myself.  Again, I was just following through the README instructions.

**Comment by prescottprue** [comment]
@gregfenton If you want a nice starter that extends create-react-app and has the setup for cypress-firebase, you should checkout [generator-react-firebase](https://github.com/prescottprue/generator-react-firebase)

**Comment by gregfenton** [comment]
Very, very interesting.  I will ponder how this impacts my world view, as I'm just getting (back) into software development and this type of infrastructure was on my list of "things to do to keep building rapidly".
