### ISSUE TITLE
bug(core): problem with 'fs' when using file preprocessing

### ISSUE THREAD

**Issue by johancblom** [prescottprue/cypress-firebase#120]
I'm trying to create unit tests with Cypress on a Vue project but keep getting an error:

Error: Webpack Compilation Error
./node_modules/cypress-firebase/lib/node-utils.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\johan\VueProjects\paddock-app\node_modules\cypress-firebase\lib'

https://github.com/cypress-io/cypress-documentation/issues/714 says fs is not to be used in cypress as it is sitting in the browser. How do I go about avoiding this webpack compilation issue?

**Comment by prescottprue** [comment]
@johancblom the usage of fs is only within the plugin which is actually the node environment, not the browser, so things should work fine. Can you provide a repo where the issue can be reproduced?

**Comment by johancblom** [comment]
Hi, thank you for getting back to me. I'm using v1.1.0. I have no working repo I can share at the moment, but from what you are saying is it the case that the plugin should not end up in a webpack bundle, or, should that part of the code be bundled in a 'node' target area perhaps.

**Comment by prescottprue** [comment]
I see that you are doing preprocessing to get the setup working. It may have to do with the fact that the plugin is going into a webpack bundle, but I thought that Cypress would still handle that case since it is in a plugin instead of the browser/test environment (where the preprocessing is being applied)

Out of curiosity, what is the preprocessing for exactly?

**Comment by johancblom** [comment]
Yes! that did the trick, thank you so much, I was going round in circles.

The preprocessing is needed for a cypress unit testing module for vue, see https://github.com/bahmutov/cypress-vue-unit-test#bundling

**Comment by prescottprue** [comment]
Thanks for letting me know it worked, we should add this to a section of the README in case other folks run into the same

**Comment by prescottprue** [comment]
Add a note to the README, so going to close. Thanks for reporting!

**Comment by cchatfield** [comment]
@prescottprue  Could you add this to the package.json?

  "browser": {
    "fs": false,
    "os": false,
    "path": false
  },

**Comment by prescottprue** [comment]
@cchatfield Can you open up a new issue describing what this change would accomplish? Also preferably with a repro for the issue

As mentioned above only certain sections of the library are actually meant for node where the rest are loaded in the browser by cypress, so I'm hesitant to in global settings without a full understanding of impact

**Comment by dpsthree** [comment]
I'm having this issue as well, but I'm using Angular with NX to structure my app. The Webpack configuration is intentionally hidden behind the tooling.

**Comment by prescottprue** [comment]
@dpsthree Can you possible open a new issue with a repro? That way I can make sure I'm reproducing correctly

I though I had this working in an NX app that was React, but maybe I'm remembering wrong

**Comment by dpsthree** [comment]
@prescottprue I'll look into that. Meanwhile, @cchatfield's recommendation worked for me. I modified the cypress-firebase package.json, but I'd rather not do that as a solution.

**Comment by dpsthree** [comment]
created #214
