### ISSUE TITLE
Tasks not registered as functions on `cy`

### ISSUE THREAD

**Issue by mrsimpson** [prescottprue/cypress-firebase#121]
## What's the issue?

The functions which should be attached to the `cy` object are not available:
`cy.login is not a function`
Also other functions which should be attached to the plugin are not there.

## What I've done

Taking first steps on Cypress, I followed the [setup guide](https://github.com/prescottprue/cypress-firebase#setup).
I am using a createReactApp based setup now, so I also followed the [example](https://github.com/prescottprue/cypress-firebase/tree/master/examples/basic), but this seems to be somewhat outdated: `cypress-firebase createTestEnvFile` fails

## How to reproduce

You can check out the [branch in my repo](https://github.com/sharemycart/sharemycart/tree/e2e-testing) and execute cypress.
_Remark: I removed the FB config in the [commands](https://github.com/sharemycart/sharemycart/blob/17b175e0367d2e6bbd6ff81f57d73c1ff3cec908/cypress/support/commands.js) before pushing it._

<img width="707" alt="Bildschirmfoto 2020-04-21 um 15 54 47" src="https://user-images.githubusercontent.com/17176678/79876411-4c5df280-83eb-11ea-8cfc-388c2d28b0fa.png">

I'm quite sure the issue is on my end and my understanding.
The library looks well architectured and understandable, but I couldn't get it working during the past four hours.

**Comment by prescottprue** [comment]
Yeah, the examples need to be updated to the v1 syntax.
As for your issue - you are sure you setup the plugin? Are you able to provide the repo where I can reproduce the error?

**Comment by prescottprue** [comment]
It looks like the `commands.js` isn't being loaded in an `index.js` file of any type [as done here](https://github.com/prescottprue/cypress-firebase/blob/master/examples/basic/cypress/support/index.js#L17) - that would mean that your commands.js file isn'e being loaded. `cypress/support/index.js` should have been included by default by Cypress, but I'm going to add something to the docs about it as well

**Comment by mrsimpson** [comment]
ah yes 🙈 
I was expecting too that the Cypress framework is taking care of loading everything inside `./cypress`.
I now added a index-file to the folder and it loads the commands.
Now I can continue with the actual setup.

Thanks a ton for the quick response, Scott! This established my capability of continuing at night ;)

**Comment by prescottprue** [comment]
Really glad to hear! I added a note about it to the docs and updated the examples to the new API. Hope it helps, happy coding!
