### ISSUE TITLE
feat(core): support namespacing of cypress custom commands

### ISSUE THREAD

**Issue by RiZKiT** [prescottprue/cypress-firebase#122]
I would like to test your plugin, but we already have custom commands like cy.login, cy.register and cy.logout. These names are very common.

It would be nice if the commands for this plugin would be prefixed, like `cy.firebaseLogin`, this also describes the use case better.

**Comment by prescottprue** [comment]
I have thought this might cause some issues, I'll look into adding that, thanks for reaching out!

**Comment by prescottprue** [comment]
This feature was added in [v1.2.0](https://github.com/prescottprue/cypress-firebase/releases/tag/v1.2.0) under the option `commandNames`. It can be used like so:

```js
const options = {
  // Key is current command name, value is new command name
  commandNames: {
    login: 'newNameForLogin',
  }
}
attachCustomCommands({ Cypress, cy, firebase }, options);
```

Also [added a section to the README](https://github.com/prescottprue/cypress-firebase#changing-custom-command-names) with the same example for other folks that may want to do the same. Thanks for reaching out with the request!

**Comment by RiZKiT** [comment]
Well that was quick, thanks!
