### ISSUE TITLE
Enabling Cypress code-coverage fails against cy.callFirestore()

### ISSUE THREAD

**Issue by gregfenton** [prescottprue/cypress-firebase#129]
I have installed [code-coverage](https://docs.cypress.io/guides/tooling/code-coverage.html#Install-the-plugin) for Cypress.

My test against my app work just fine.  But my tests that call `cy.callFirestore()` fail with:

> cy.task('callFirestore') failed with the following error:
> 
> The task 'callFirestore' was not handled in the plugins file. The following tasks are registered: resetCoverage, combineCoverage, coverageReport
> 
> Fix this in your plugins file here:
>     /Users/merpy/work/tick8s/cypress/plugins/index.js
> 
> https://on.cypress.io/api/task

If I disable the code-coverage configuration in Cypress, the `cy.callFirebase()` tests works just fine.

It seems there is a need to expose `callFirestore` to the ["code instrumentation" process](https://docs.cypress.io/guides/tooling/code-coverage.html#Instrumenting-code).  This might be a fairly straight-forward thing, but I'm not sure how best to do it in a create-react-app built app that is using cypress-firesbase.  Again, my other tests (all pure cypress API) work just fine.

**Comment by prescottprue** [comment]
Are you sure you included the plugin? The list of tasks doesn’t seem to include any of the custom cypress-firebase tasks. Can you share the repo so I can be sure to reproduce the issue?

**Comment by gregfenton** [comment]
I struggled trying to get the examples/basic project running.  I was getting TypeScript errors within Cypress complaining about extendWithFirebaseConfig not being a function.  I wasted too much time on it so I built my own simple app along with reproduction steps:

https://github.com/gregfenton/cypress-firebase-code-coverage

See the README at the root of the project.  Should take 5-10 minutes to get the repro going, depending on whether you go with my Firebase project or you create your own.

(If I remember, I'll tear down that serviceAccount in the next few days, so please let me know if/when you have validated the issue  (by "you" I mean the wider github audience...this doesn't all have to fall to @prescottprue !)

**Comment by prescottprue** [comment]
Thanks for the repro - I'll look into it. I have not kept the examples of this repo as up to date as I should, but instead have mostly been using cypress-firebase in different projects. Glad to have folks like you reminding me to come back and clean up the example/docs - the PRs are much appreciated 😄

**Comment by gregfenton** [comment]
I'm pretty certain this is just going to be a build or runtime config thingy.  Somehow we need to convince @cypress/code-coverage and/or nyc to "instrument" callFirestore().  My app code is just fine, including all the npms I am using.  But cypress-firebase is exposed directly to Cypress, so it isn't going through the same build/startup routines.

**Comment by bahmutov** [comment]
You have overriden the plugins file and only register code coverage tasks. You file should read

```js
const admin = require("firebase-admin");
const cypressFirebasePlugin = require("cypress-firebase").plugin;
module.exports = (on, config) => {
   cypressFirebasePlugin(on, config, admin);   
   require('@cypress/code-coverage/task')(on, config)
   return config
}
```

**Comment by gregfenton** [comment]
Brilliant, thank you.  With the above, I am now running my cypress-firebase tests *with code-coverage*!!

Wasn't clear to me that the **same** module.exports was to be used for both code-coverage and other tasks.  I'll put up a PR for the code-coverage README to help others in the future.

Thanks @bahmutov and @prescottprue !!!

**Comment by prescottprue** [comment]
Thanks for posting @bahmutov that is right!

If you want the config extending that happens through the plugin as well you can do the following:

```js
const admin = require("firebase-admin");
const cypressFirebasePlugin = require("cypress-firebase").plugin;
module.exports = (on, config) => {
   const newConfig = cypressFirebasePlugin(on, config, admin);   
   require('@cypress/code-coverage/task')(on, config)
   return newConfig
}
```

**Comment by gregfenton** [comment]
@prescottprue - want me to update the README patch accordingly?
