### ISSUE TITLE
cy.callFirestore is not a function

### ISSUE THREAD

**Issue by scowling** [prescottprue/cypress-firebase#142]
Firstly - this may be a setup problem. My cypress testing files are within a NX workspace, but without cypress-firebase cypress itself runs fine.
The link in the documentation "See the folders section below for more info about other supported folders" doesn't actually go anywhere so I can't check this out.

I have installed the plugin as per the instructions (the NPM instructions are slightly different to the github ones
NPM: 
`module.exports = (on, config) => {
  return cypressFirebasePlugin(on, config, admin);
};`
Github:
`module.exports = (on, config) => {
  const extendedConfig = cypressFirebasePlugin(on, config, admin)
  return extendedConfig
};`

For reference my setup is this:
`module.exports = (on, config) => {
  const extendedConfig = cypressFirebasePlugin(on, config, admin)
  on('file:preprocessor', preprocessTypescript(config));
  return extendedConfig;
};`

I have added a single call to a test that was already working:
`cy.callFirestore("add", "test_hello_world", { some: "value" });`

And I receive the error cy.callFirestore is not a function
> 14 |     cy.callFirestore("add", "test_hello_world", { some: "value" });

I'm not sure what to try next

**Comment by prescottprue** [comment]
@scowling quick question about the setup - do you need the file:preprocessor? I was under the impression that cypress handles typescript out of the box now - thought I saw that in their release notes a short while back.

As for the main issue, looks like there is an issue with the custom commands not being loaded. Are you sure you followed all of the [setup steps in the README](https://github.com/prescottprue/cypress-firebase#setup) (specifically step number 5)

**Comment by scowling** [comment]
Yep that is in there, although VS code is complaining that 
`cypress-firebase/index.d.ts' is not a module.ts(2306)`

The only other stuff in commands.ts is the example boilerplate that cypress has in there

Regarding the preprocessor - I only installed cypress yesterday and that is the default setup. I can remove it if you think it might be the problem

**Comment by scowling** [comment]
any thoughts here @prescottprue ?
I've tried alternate ways to import the attachCustomCommands module into commands.ts but cypress is having none of it. And VS Code still complains that cypress-firebase is not a module.

**Comment by prescottprue** [comment]
@scowling Did you log in that file to make sure it is being called? If cy.callFirestore is not set, then I'm almost positive it is coming down to something with attachCustomCommands

The not finding the module seems really weird - since you just started are you able to share your repo so that the issue can be reproduced? Going to try to repro on my end again later today as well

**Comment by scowling** [comment]
sorry @prescottprue it's not an empty project - just that I have just added cypress - I can't share it

Could the complication be related to the fact that it's in an NX workspace?
Folder structure is like this:
* apps
  * main_app
  * main_app-e2e
    * src
      * fixtures
      * integration
      * plugins
      * support
    * cypress.json

I dismissed that as a problem because cypress actually runs and performs the smoke test - and then fails on `expect(cy.callFirestore).to.be.a('function')`

**Comment by scowling** [comment]
Bingo! @prescottprue 
Coming back to this with a clear head on Monday morning. It was file location.
I moved the command and plugin stuff to a cypress directory in the root. Even though cypress is configured to pickup tests in the nested folder.

Thanks for your help

**Comment by prescottprue** [comment]
Happy to hear, thanks for the update. Now I know to mention checking for that in the future!
