### ISSUE TITLE
chore(docs): remove references to old API including createTestEnvFile

### ISSUE THREAD

**Issue by ncko** [prescottprue/cypress-firebase#143]
I'm having issues setting environment variables for firebase on CI/CD (github actions). The README mentions `createTestEnv` at the top of the file. `createTestEnv` appears to be a command passed to a command line script (`$> cypress-firebase createTestEnv`).

However, I can't actually find this script, and I find instructions for it in previous versions of this repo. I did find instructions on setting the CYPRESS_TEST_UID and SERVICE_ACCOUNT environment variables, however that has not made a difference as far as I can tell.

Any advice on how I can use this plugin in CI/CD?

**Comment by prescottprue** [comment]
It has actually been removed, so looks like that part of the docs need a bit of updating.

In CI I commonly select settings from the `.firebaserc` using bash then expose those as environment variables prefixed with `CYPRESS` so they are passed to the cypress env. If you would like a reference, might be worth checking out the [CI setup of another project I started called fireadmin](https://github.com/prescottprue/fireadmin/blob/master/.github/workflows/app-verify.yml#L82-L163), specifically the part where [the branch is used to select specific env variables](https://github.com/prescottprue/fireadmin/blob/master/.github/workflows/app-verify.yml#L122-L132) pulled from secrets

I'll work on trying to add an example using similar logic to the docs of cypress-firebase

**Comment by ncko** [comment]
Thank you so much! That was extremely helpful.

**Comment by prescottprue** [comment]
Working on adding a  `setEnv` command to firebase-ci which sets environment variables based on settings matching branch name within .firebaserc and supports renaming existing vars i.e.:


```json
{
  "ci": {
      "setEnv": {
      "master": {
        "MY_VAR": "some var value",
        "MY_OTHER_VAR": "${EXISTING_ENV_VAR}",
        "REACT_APP_SOME_VAR": "some var passed to react",
      },
      }
  }
}
```

[Here is the settings being used in fireadmin](https://github.com/prescottprue/fireadmin/blob/master/.firebaserc#L9), which is using the alpha version of firebase-ci since this hasn't been released to latest yet
