### ISSUE TITLE
feat(plugin): support for providing a path to a custom path serviceAccount

### ISSUE THREAD

**Issue by tcrwt** [prescottprue/cypress-firebase#148]
Thanks very much for this library. The instructions suggest that I must include a `serviceAccount.json` file in the root. I was keen to avoid this, as we have the same information saved under a different file name in a different directory, for use in other tests.

If I could point cypress-firebase to the information from this file, this would save us having two copies of the same information in two places (and save devs copying the file twice).

I think I've been able to achieve this, so thought I'd check I'm doing the right thing. If I am, perhaps this could be added to the documentation in case others have the same use case.

It required this change to `plugins/index.js`, at step 7 in the [README.md](https://github.com/prescottprue/cypress-firebase/blob/master/README.md).
```ts
// plugins/index.js

const admin = require('firebase-admin');
const cypressFirebasePlugin = require('cypress-firebase').plugin;

module.exports = (on, config) => {
    // This is my abcde.firebaseio.com URL. An env variable but could just be inline.
    const firebaseURL = config.env.FIREBASE_DB_URL;

    // This is the path of my `serviceAccount.json` file, relative to the `plugins` folder. An env variable but could just be inline.
    const firebaseKeyPath = config.env.FIREBASE_SERVICE_ACCOUNT_KEY;
    // Import the json file using this path 
    const serviceAccount = require(firebaseKeyPath);

    admin.initializeApp({
        credential: admin.credential.cert(serviceAccount),
        databaseURL: firebaseURL,
    });

    // Below this point is the same as in README.md 
    const extendedConfig = cypressFirebasePlugin(on, config, admin);
    return extendedConfig;
};
```

**Comment by prescottprue** [comment]
Nice, thanks for sharing. This should be a perfectly fine way of doing it from what I can tell, especially since internally we check if the app has already been initialized before initializing.

One issue that may arise is support for emulators - if `FIREBASE_EMULATOR_HOST` and/or `FIREBASE_DATABASE_EMULATOR_HOST` as set, then [internally the admin instance will be initialized pointed to the emulators](https://github.com/prescottprue/cypress-firebase/blob/master/src/firebase-utils.ts#L68-L99). This may not be a concern for you though if you are not using them

**Comment by tcrwt** [comment]
Thanks – glad to hear it's vaguely sensible!

I hadn't thought about the emulators. As you mention, not a concern for my use case as I'm not using them. Perhaps that's enough of a complication to mean that it's safest/simplest not to add this to the readme.

**Comment by prescottprue** [comment]
I think it would be easy enough to add support for a custom path through an env variable [on this line where we point to the service account](https://github.com/prescottprue/cypress-firebase/blob/master/src/firebase-utils.ts#L84)

**Comment by prescottprue** [comment]
Worth note: `SERVICE_ACCOUNT` is and environment variable which is currently supported for handling a service account object [as noted in the CI considerations section of the README](https://github.com/prescottprue/cypress-firebase/blob/master/README.md#considerations-for-ci). That said, still planning to add an env variable for path to a file

**Comment by prescottprue** [comment]
Also wanted to callout that there is support for default credentials, so if you set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to the path to your service account it will be loaded by default (without needing to place contents of the service account within a environment variable).

Please reach out if you are experiencing an issue and we can reopen
