### ISSUE TITLE
feat(commands): ability to check auth user from cy command

### ISSUE THREAD

**Issue by bailejl** [prescottprue/cypress-firebase#15]
Your plugin is great.  It save me a lot of time with my Cypress testing.  I have a need to access the Firebase Admin tool from my testing. Basically, I want to verify user are created correctly, for now.  Are you interested in expanding this plugin?  If so, I would like to help.

**Comment by prescottprue** [comment]
Glad to hear it helped 😄 

Yes definitely interested in the feature! Had already been thinking of this as a feature and just having gotten to it yet (assuming you are talking about verifying user's created in the auth tab). This feature or any others are always welcome as PRs, but I will try to get to it in the next few weeks if you don't get a chance. Thanks for reaching out!

**Comment by bailejl** [comment]
@prescottprue Glad you are interested in the feature.  

Yes, I was talking about the auth tab.  :-)

**Comment by prescottprue** [comment]
v1.2.0 has the new `cy.getAuthUser` custom command which can be used to load auth users by UID. Thanks for the feature request!
