### ISSUE TITLE
Object with null value throws an error

### ISSUE THREAD

**Issue by bartlomiejborzucki** [prescottprue/cypress-firebase#150]
I want to add object  to the firebase/firestore  with null value 
newObject = {
name: 'new object',
finishDate: null
}
I've used this function:
cy.callFirestore("set", "task", newObject );

 I've got an error in the bold part of the below code (src/tasks.ts:80): 
if (
	 typeof data[currKey] === 'object' &&
	 /* eslint-disable-next-line no-underscore-dangle */
	 **!data[currKey]._methodName &&**
	 !data[currKey].seconds &&
	 !Array.isArray(data[currKey])
	 )  
Because currKey is set to 'finishDate' and date[finishDate] is null and data[currKey]._methodName throws an error. 
IMHO it is a regression bug because I got this error after update from 1.0 to 1.4.2. 
Is it a bug? Could you fix it?

**Comment by prescottprue** [comment]
It definitely was an issue and regression thanks for reporting! Fixed [in v1.4.3](https://github.com/prescottprue/cypress-firebase/releases/tag/v1.4.3). I also added a test case for null values, so we shouldn't see this one pop up again
