### ISSUE TITLE
bug(types): types don't seem to be working properly

### ISSUE THREAD

**Issue by nicholaschiang** [prescottprue/cypress-firebase#173]
**Describe the bug**

I've done the following and keep coming across Typescript compilation bugs (even though this was supposedly addressed in #47):
1. Added the package as a `devDependency` using `yarn`:
```
$ yarn add cypress-firebase -D
```
2. Configured a [`cypress/tsconfig.json`](https://github.com/tutorbookapp/tutorbook/blob/cypress/cypress/tsconfig.json) file to include the Cypress package (as was done in [this example](https://github.com/prescottprue/cypress-firebase/tree/master/examples/typescript)):
```json
// cypress/tsconfig.json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "isolatedModules": false,
    "lib": ["es5", "dom"],
    "types": ["cypress", "node", "cypress-firebase"]
  },
  "include": ["../node_modules/cypress", "**/*.ts"]
}
```
3. Edited the [`cypress/support/commands.ts`](https://github.com/tutorbookapp/tutorbook/blob/cypress/cypress/support/commands.ts) file to (essentially) match what's in [your example](https://github.com/prescottprue/cypress-firebase/blob/master/examples/typescript/cypress/support/commands.ts):
```typescript
// cypress/support/commands.ts
import path from 'path';

import { attachCustomCommands } from 'cypress-firebase';
import dotenv from 'dotenv';
import firebase from 'firebase/app';

import 'firebase/auth';
import 'firebase/firestore';
import 'cypress-file-upload';

dotenv.config({ path: path.resolve(__dirname, '../../.env') });

const clientCredentials = {
  apiKey: process.env.FIREBASE_API_KEY,
  authDomain: process.env.FIREBASE_AUTH_DOMAIN,
  databaseURL: process.env.FIREBASE_DATABASE_URL,
  projectId: process.env.FIREBASE_PROJECT_ID,
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.FIREBASE_APP_ID,
  measurementId: process.env.FIREBASE_MEASUREMENT_ID,
};

if (!firebase.apps.length) firebase.initializeApp(clientCredentials);

attachCustomCommands({ Cypress, cy, firebase });
```
4. Ran into the follow ESLint errors when editing in Vim (I'm using [ALE](https://github.com/dense-analysis/ale) to asynchronously call ESLint which compiles the Typescript as I work):
```
File '/home/nchiang/repos/tutorbook/node_modules/cypress-firebase/index.d.ts' is not a module.
```
And then because of that error, Typescript can't find a type definition for the `attachCustomCommands` function:
```
@typescript-eslint/no-unsafe-call: Unsafe call of an any typed value.
```

**To Reproduce**

1. Clone [this repository](https://github.com/tutorbookapp/tutorbook):
```
$ git clone https://github.com/tutorbookapp/tutorbook
```
2. Check out to the `cypress` branch:
```
$ git checkout cypress && git pull
```
3. Install dependencies (or follow [these instructions](https://github.com/tutorbookapp/tutorbook/tree/cypress#development-environment)):
```
$ yarn install
```
4. Open up `cypress/support/commands.ts`, run ESLint, and see the error.

**Expected behavior/code**
Typescript should be able to pick up the definitions in `node_modules/cypress/index.d.ts` and properly detect the `attachCustomCommands` definition (along with adding the custom commands to the global `Cypress` object).

**Additional Context/Screenshots**

![image](https://user-images.githubusercontent.com/20798889/92199561-5b8a8d80-ee2c-11ea-8289-bd30096cb31d.png)

**Comment by nicholaschiang** [comment]
Make sure to checkout to the `51922c2` commit hash because I'm going to push some new changes to that branch (removing the `cypress-firebase` dependency as a temporary fix).

**Comment by prescottprue** [comment]
Interesting, I will look at the replication. [The typescript example](https://github.com/prescottprue/cypress-firebase/tree/master/examples/typescript) seems to pickup on the type definitions, so wondering if it something else with the build setup. Do you also see this when you run eslint or typescript directly without ALE?

**Comment by dpsthree** [comment]
I ran into this today as well.

**Comment by cchatfield** [comment]
temp workaround:

import { attachCustomCommands } from 'cypress-firebase/lib';

**Comment by prescottprue** [comment]
Please give [v2.2.0](https://github.com/prescottprue/cypress-firebase/releases/tag/v2.2.0) a try - there is a fix for types in there. There is more info in the PR, but it basically had to due with duplicate type defintions due to scripts from before cypress-firebase was written in TS.

If issues remain we can reopen, but the [Typescript example](https://github.com/prescottprue/cypress-firebase/tree/main/examples/typescript) now uses [TS for Cypress folder as well](https://github.com/prescottprue/cypress-firebase/tree/main/examples/typescript/cypress) without issue.
