### ISSUE TITLE
Question: how does this library knows which project to work on, when using FIREBASE_TOKEN?

### ISSUE THREAD

**Issue by christopher-francisco** [prescottprue/cypress-firebase#179]
Sorry for the silly question.

For regular Firestore operations, `serviceAccount.json` is used, so I can trust it will act on the project I intend it to. However, when using `FIREBASE_TOKEN` for `delete` operation, how does it know what project to work on?

I believe the token itself give you access to all projects, so is there a chance I would run a `delete` on a different project? 

I'm particularly keen on this since I manage both staging and prod from the same laptop

**Comment by prescottprue** [comment]
Thanks for reaching out! Guessing you found that in the README? That part appears to be out of date - all operations now go through firebase-admin so they use the service account as you mentioned. Going to leave this issue open as a way to track updating that

**Comment by christopher-francisco** [comment]
@prescottprue I had assumed it'd use firebase-admin's serviceAccount for most of the operations, but I'm talking specifically about the `delete` operation on Firestore. Documentation says it uses a `FIREBASE_TOKEN` (instead of serviceAccount.json) because it uses `firebase-tools` rather than `firebase-admin`.

Moreover, a `FIREBASE_TOKEN` has access to all of my projects, so I wonder how does the knows which one to run the delete operation on, as the docs doesn't seem to receive the project name as an argument when running `delete` operations

**Comment by prescottprue** [comment]
Right - that part of the documentation is no longer correct. All of the commands use the service account with firebase-admin. FIREBASE_TOKEN is for firebase-tools which is no longer used. Will try to update the docs tomorrow

**Comment by prescottprue** [comment]
Updated the docs to remove that, thanks for reaching out!
