### ISSUE TITLE
bug(callFirestore): timestamps not working in arrays

### ISSUE THREAD

**Issue by A13k2** [prescottprue/cypress-firebase#181]
**Describe the bug**

When using timestamps in arrays, they are not properly represented in the database.

**To Reproduce**

1. Run:
```typeescript
cy.callFirestore('set', `tests/testTimestamp`, {
      a: [firebase.firestore.Timestamp.now()],
    } as CallFirestoreOptions);
```
2. Database shows:
![Screenshot 2020-09-14 at 10 41 02](https://user-images.githubusercontent.com/18004529/93063608-ccc11080-f676-11ea-817d-6afa924c235b.png)

**Expected behavior/code**
Data should be a timestamp.

**Additional Information**
Running
```typeescript
cy.callFirestore('set', `tests/testTimestamp`, {
      a: firebase.firestore.Timestamp.now(),
    } as CallFirestoreOptions);
```
gives the expected result:
![Screenshot 2020-09-14 at 10 42 50](https://user-images.githubusercontent.com/18004529/93063792-0d208e80-f677-11ea-83ee-2e08f29c6482.png)

**Comment by prescottprue** [comment]
The fix for this and an accompanying test was included in [the v1.4.5 release](https://github.com/prescottprue/cypress-firebase/releases/tag/v1.4.5) - reach out if it is not working as expected. Thanks for reporting!

**Comment by A13k2** [comment]
Hey @prescottprue its working now! Thanks for the quick fix.

I just noticed that it still doesn't work for objects in arrays 🙈 , e.g.:
`
cy.callFirestore('set', `tests/testTimestamp`, {
      a: [{test: firebase.firestore.Timestamp.now()}],
    } as CallFirestoreOptions);
`

**Comment by A13k2** [comment]
@prescottprue i forked your repo and implemented a fix with tests:
https://github.com/A13k2/cypress-firebase/commit/a8a79282bd9b4fdc6335c590dbafe2607c17a64a

I didn't contribute to open source projects before, so just let me know what to do with it 😄 

We are using your plugin quite extensively for our project, so we would be open to contribute some more in the future...

Amazing project btw, helps us a lot and it was easy to understand the code and write my fix/ tests for it 👍

**Comment by A13k2** [comment]
Hey @prescottprue ,

just noticed that this is still not working for arrays in objects.

Will this be fixed soon?

**Comment by A13k2** [comment]
Still not working @prescottprue....

Please reopen

**Comment by ygd** [comment]
second that
