### ISSUE TITLE
feat(auth): tenant support

### ISSUE THREAD

**Issue by jonespen** [prescottprue/cypress-firebase#194]
**Is your feature request related to a problem? Please describe.**

We're using [Cloud Identity with multiple tentants](https://cloud.google.com/identity-platform/docs/multi-tenancy), but doesn't seem like this library supports setting a [`tenantId` for `firebase.auth()`](https://firebase.google.com/docs/reference/admin/node/admin.auth.Tenant). 

**Describe the solution you'd like**

A way of setting `tenantId` for `firebase.auth()`

**Describe alternatives you've considered**

I looked at the source, and found no way of passing parameters to `firebase.auth()`

**Additional context**

I'd be happy to create a pull request with a proposed solution.

**Comment by prescottprue** [comment]
Thanks for reaching out! I think this should definitely be supported.

Guessing your app is already handling the client side of changing tenantId and you would be looking to do that within the `firebase-admin` instance running on the node side, is that correct? If some maybe we can pass that along as an option when calling cy.login?

Would love if you made a PR if you already have some changes in mind

**Comment by jonespen** [comment]
Yes, sorry for the delay, I’ll try to cook up something tomorrow
