### ISSUE TITLE
bug(commands): can not log out correctly with cy.logout()

### ISSUE THREAD

**Issue by molchiro** [prescottprue/cypress-firebase#20]
It helps me a lot to test the firebase project. Thanks.

But, cy.logout() don't run correctly.

In logout command, you use 'firebase.auth().currentUser'.
The official document says currentUser might also be null because the auth object has not finished initializing.
https://firebase.google.com/docs/auth/web/manage-users?hl=en#get_the_currently_signed-in_user

So, it is better to use onAuthStateChanged method, as your login command.

**Comment by prescottprue** [comment]
Fixed in v0.2.0-alpha.5 available from the `next` tag (i.e. `npm i cypress-firebase@next`)

**Comment by molchiro** [comment]
Thanks a lot. I will try to use it now!

**Comment by prescottprue** [comment]
v0.2.0 also includes removing the `cy.log` which can cause a cypress log warning about promises in some cases
