### ISSUE TITLE
Authenticating in CI

### ISSUE THREAD

**Issue by idrisadetunmbi** [prescottprue/cypress-firebase#21]
Is there a provision for an alternative to `serviceAccount.json` since it can't possibly be checked in to VC to be used in the CI? There are some CI variables stated in the readme, but they only apply to other firebase tools used by the library.

**Comment by prescottprue** [comment]
`SERVICE_ACCOUNT` is a supported environment variable that was added in [v0.1.5](https://github.com/prescottprue/cypress-firebase/releases/tag/v0.1.5), setting this environment variable to a string which contains the service account object will take precedence over the `serviceAccount.json`.

That said, with older versions, you can put a simple command before your using firebase-ci that turns an environment variable string into a file (i.e. `SERVICE_ACCOUNT > ./serviceAccount.json`)

**Comment by prescottprue** [comment]
Going to close since I believe this has been answered - feel free to post if you still have questions
