### ISSUE TITLE
Can't resolve 'fs' on Angular Nx projects

### ISSUE THREAD

**Issue by dpsthree** [prescottprue/cypress-firebase#214]
After following the setup from the README and adding the work around from #173 I receive the attached error:
<img width="1918" alt="error" src="https://user-images.githubusercontent.com/1540699/97349414-7510ea00-185d-11eb-881b-fcaad04c225f.png">

Repro can be found here: https://github.com/dpsthree/cypress-firebase-repro
npm install
npm run e2e:watch
select example.spec.ts from the test spec list

It should run without error

Adding:
"browser": {
  "fs": false,
  "os": false,
  "path": false
},
to the package.json of cypress-firebase resolves the issue, but is not a good solution for the consuming developer to add it.

Nx project was created with the following CLI commands:
<img width="1152" alt="install" src="https://user-images.githubusercontent.com/1540699/97349968-21eb6700-185e-11eb-87a6-9a63f6ecbf77.png">
<img width="1152" alt="npx setup" src="https://user-images.githubusercontent.com/1540699/97349970-2283fd80-185e-11eb-98c6-015a3aeb445d.png">

**Comment by prescottprue** [comment]
Thanks for reporting with the repro! We should be able to give the change you mentioned with the package.json a try - it shouldn't impact the node side of things. Will put it on a next/alpha release so we can confirm though

**Comment by DG-za** [comment]
Just wanted to add that I'm running into the same issue with an Nx project and the same fix worked for me.

**Comment by prescottprue** [comment]
v1.6.0-alpha was released to the `next` tag with the change to the package file - going to do some more testing when I get a chance, but would love to hear from anyone that gets a chance to try it out

**Comment by dpsthree** [comment]
1.6 alpha is working well for me without the need for a post-install modification.

**Comment by prescottprue** [comment]
@dpsthree great to hear - thanks for the update

**Comment by DG-za** [comment]
Same here, I haven't tested everything, but initial cypress startup and my cypress-firebase related tests seemed to work fine with the alpha.
