### ISSUE TITLE
Firebase authentication emulator support

### ISSUE THREAD

**Issue by tombeckenham** [prescottprue/cypress-firebase#252]
**Is your feature request related to a problem? Please describe.**

Looking to use the new firebase authentication emulator for local cypress testing & ci. I can seed with a list of users, but then would like to login using email / password rather than uid

**Describe the solution you'd like**

Ideally add a login command to allow me to login using email / password rather than uid. Also build in the ability to seed auth with a list of users

**Comment by prescottprue** [comment]
Will have to think on this one a bit - even if you have an account that was made with email/password login the `cy.login` command creates a custom custom token as that user

I think that connection to the auth emulator is a separate piece, which should be supported, so I'll look into that. Do you do the following when you are initializing the firebase app within cypress:

```
firebase.auth().useEmulator('http://localhost:9099/');
```

Presumably you have logic similar to ^ in your app code so it can be used with the emulator, but may also be needed when initializing firebase in Cypress

**Comment by wajeehmisbahkhan** [comment]
Can we expect something like cy.callAuth('create user', userObject) or something to the effect in the near future? In which case the login functionality can also be included cy.callAuth('login', uid).

**Comment by itsravenous** [comment]
Leaving the seeding of users aside, it would be great to support the auth emulator even just for `cy.login()`. I did try running with `FIREBASE_AUTH_EMULATOR_HOST=localhost:9099` but it doesn't seem to get passed through to `firebase-admin` for some reason - I get this error:

```
CypressError: `cy.task('createCustomToken')` failed with the following error:

> Failed to determine service account. Make sure to initialize the SDK with a service account credential. Alternatively specify a service account with iam.serviceAccounts.signBlob permission. Original error: Error: Error while making request: getaddrinfo ENOTFOUND metadata. Error code: ENOTFOUND
```

which I would expect if running without credentials loading if I _hadn't_ set the auth emulator env var.

**Comment by prescottprue** [comment]
Support added in [v1.7.0](https://github.com/prescottprue/cypress-firebase/releases/tag/v1.7.0) - please reach out if it isn't functioning as expected

**Comment by itsravenous** [comment]
Seems to work for me, thanks! :tada:
