### ISSUE TITLE
cy.callFirestore('update', {}) is not updating the database.  

### ISSUE THREAD

**Issue by naddiebell** [prescottprue/cypress-firebase#345]
**Describe the bug**

When I use 
cy.callFirestore('update', `users/${example1}`, {
   name: 'Example'
})

and then I check the db, nothing has been updated.  But when I use cy.callFirestore('set'), it is working, as well as delete.

**Comment by prescottprue** [comment]
There are a few different places this functionality is tested against a real DB and I am not able to replicate. Please provide a complete example where this can be replicated so I can debug further.

**Comment by AurelienLoyer** [comment]
I was facing the same issue, looking this close issue, and... i got a fix 🤩
On my side, `get` action for `cy.callFirestore` was working well. Only `update` `set` ... wasn't 😢

Adding the `{ projectId: 'e2eprojectid' }` to the **cypressFirebasePlugin** conf solved my issue 🎉

```js
const admin = require('firebase-admin');
const cypressFirebasePlugin = require('cypress-firebase').plugin;

module.exports = (on, config) => {
    cypressFirebasePlugin(on, config, admin, { projectId: 'e2eprojectid' });
};
```
