### ISSUE TITLE
fbConfig databaseUrl undefined even when set

### ISSUE THREAD

**Issue by spnkdev** [prescottprue/cypress-firebase#361]
**Describe the bug**

I get a warning saying that the database url is undefined but I'm setting it as indicated on the instructions.

**To Reproduce**

```
/* eslint-disable import/no-extraneous-dependencies */
import firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/database';
import { attachCustomCommands } from 'cypress-firebase';

const fbConfig = {
  databaseURL: 'https://ieai-test.firebaseio.com'
};

firebase.initializeApp(fbConfig);

// eslint-disable-next-line no-undef
attachCustomCommands({ Cypress, cy, firebase });

```

If I log the `fbInstance `inside the library, it shows that there is the `projectId `and `credential `properties filled but no databaseUrl property.

I did the entire process by copy paste to avoid errors, but since its a entry level bug there might be something I'm missing.

```
"firebase": "^8.5.0",
"cypress-firebase": "^1.8.0",
"firebase-admin": "^9.5.0",
```

**Comment by prescottprue** [comment]
Did you include the other config params in the `fbConfig` object like `projectId`, `apiKey`, `authDomain`? `credential` shouldn't need to be passed?

Is the warning you are seeing within the Cypress environment? How are you initializing firebase within your app?

**Comment by prescottprue** [comment]
I think I may have actually tracked this down to a bug that was introduced in v1.8.1 - looking to confirm that and work on a fix now

**Comment by prescottprue** [comment]
I ended up finding that this was most likely due to a bug introduced in v1.8.1 with how databaseURL was being defaulted for the internal firebase instance. v1.9.1 includes a fix for that bug as well as a test to cover that case

Let me know if things are still not working as expected and we can reopen.

Thanks for reporting!
