### ISSUE TITLE
question(angular): Is Angular with AngularFire supported?

### ISSUE THREAD

**Issue by xKelvin** [prescottprue/cypress-firebase#389]
While trying to use the library with the firestore emulator I noticed that the library is dependent on some `process.env` vars as [you can see here.](https://github.com/prescottprue/cypress-firebase/blob/master/src/firebase-utils.ts#L68-L99) This made me wonder if it is even possible to use this library with my project, given that [you can't set `process.env` vars from within Angular.](https://stackoverflow.com/a/49496585/5868830) As far as I can tell anyway, please correct me if I'm wrong

I did manage to setup the connection with my Auth emulator, but that's purely based on the defaults set within the library which correspond to the default port of the Auth emulator. These defaults are not set for firestore, so I wonder if it is possible to connect the emulated firestore to my Cypress tests in Angular?

_Sorry for not using the PR template, not sure where to ask questions like these._

**Comment by xKelvin** [comment]
What I ended up doing, for now, was setting the environment variable in the terminal, and directly after it running Cypress, like so:
Windows: `setx FIRESTORE_EMULATOR_HOST localhost:8080 && npm run cypress open`
Unix: `FIRESTORE_EMULATOR_HOST=localhost:8080 $(npm bin)/cypress open`

**Comment by prescottprue** [comment]
Hey thanks for asking - what you provided is the expected way to connect to the emulators.

The quick answer is yes! cypress-firebase is really about easy connection from your tests to a Firebase instance (emulated or hosted). The way the application is built shouldn't really have any impact on how you are testing - I've personally worked on projects where we tested apps which use vanilla JS Firebase, Redux, React (with Reactfire), and Next. If you see any problems as you are testing Angular apps, please report!
