### ISSUE TITLE
using cypress-firebase with vue cli projects

### ISSUE THREAD

**Issue by shiva** [prescottprue/cypress-firebase#41]
cypress-firebase assumes hard-coded locations for the cypress.json file among other files. vue-cli extension for cypress places the files in a different base location that is assumed by this module. Is there a way that I can customize, or pass the location of the files needed for this module to work? 

I could fork and make the changes if you have suggestions on how you'd approach fixing file paths.

**Comment by prescottprue** [comment]
As mentioned in [the folders section of the docs](https://github.com/prescottprue/cypress-firebase#folders), you can set different folders for the different files, but that is it (wouldn't handle the case of a custom `cypress.json` path).

Definitely open to a PR if you get the time, thanks for reporting!

**Comment by shiva** [comment]
I realized that the issue wasn't that my cypress.json wasn't getting loaded, it was that config.json was always being read from cypress/config.json, instead of {integrationFolder}/config.json. I will close this issue and raise that as a separate one with a PR
