### ISSUE TITLE
How to use the where option with callFirestore

### ISSUE THREAD

**Issue by damienromito** [prescottprue/cypress-firebase#501]
As the ID of my documents are generated randomly, i need to delete a queried document.
I tried the query below but this deleted all the documents of the collection => the 'where' option didn't works

**The solution I'd like :**
` cy.callFirestore('delete', 'users', { where: ['email', '==', 'test@test.com'] })`

**The alternative solution as to use two queries :** 

  cy.callFirestore('get', 'users', { where: ['email', '==', ''test@test.com'] }).then(result => {
      if (result[0].id) {
        cy.callFirestore('delete', `users/${result[0].id}`)
      }
    })

If this feature doesn't exists, this could be written on to the read.me, otherwise this could be added ? 🙃

**Comment by prescottprue** [comment]
I was actually under the impression that this was supported, so I didn't document the case directly. When I saw this issue I went back to look and not only does it not exist, but there was a comment in the code about adding it 😆 .

Thanks for posting - I added the functionality in v2.1.0 along with an example in the README

**Comment by ComradeAERGO** [comment]
It seems like this is still happening.

`cy.callFirestore('delete', `companies/${companyId}`)`
Deleted my whole `companies` collection

**Comment by prescottprue** [comment]
@ComradeAERGO could you open a new issue with what you are describing? I want to make sure we confirm this isn't still happening. Not going to have time today, but want to make sure this isn't lost

**Comment by dominics** [comment]
The where option is typed as: `where?: WhereOptions | WhereOptions[];`, assuming I'm reading the code correctly, it doesn't seem to support any more than two `where` options? (It silently ignores others? https://github.com/prescottprue/cypress-firebase/blob/885abba7068fe4a392c47dcac828d8f93e53c17a/src/firebase-utils.ts#L277)

If so, it'd be good to document that!

**Comment by prescottprue** [comment]
@dominics great callout - I wasn't aware the code was still like that. When looking at the firebase docs it also appears that with the modular API they support many OR along with the multiple wheres: https://firebase.google.com/docs/firestore/query-data/queries#web-modular-api_14

I'll look into updating, but if you get a chance, always open to a PR!

**Comment by prescottprue** [comment]
Closing since [v4.1.1](https://github.com/prescottprue/cypress-firebase/releases/tag/v4.1.1) added support for more than 2 wheres vis #1313 (thanks @dominics )

@ComradeAERGO are you sure that your id was defined in that case? There is tests against the eumulator for [deleting a document based on path](https://github.com/prescottprue/cypress-firebase/blob/main/test/unit/tasks.spec.ts#L638-L647) and [deleting a documents based on a where query](https://github.com/prescottprue/cypress-firebase/blob/main/test/unit/tasks.spec.ts#L622-L636)
