### ISSUE TITLE
Invalid token format on `cy.login`

### ISSUE THREAD

**Issue by ralphsmith80** [prescottprue/cypress-firebase#54]
I have a simple test to validate authentication.

```
describe('authentication', () => {
  before(() => {
    cy.visit('/')
    // Login using custom token
    cy.login()
  })
  after(() => {
    // disable this to see the page after login
    cy.logout()
  })

  it('should login', () => {
    cy.get('title#logoWithName').should('contain', 'Keepify')
  })
})
```

I get the following error while running cypress and my app locally as well as when running cypress locally and pointing at my actual instance firebase instance.
```
Error: The custom token format is incorrect. Please check the documentation.
```

I've created a new private key using a service account and saved it as `serviceAccount.json` as well as everything else outlined in the setup section. Everything looks like it should be working. I've validated the JWT generated on https://jwt.io/. 

If I login manually then it works hitting the `firebase.auth().currentUser` - `('Authed user already exists, login complete.')` use case but that doesn't test the token case - `signInWithCustomToken`.

Development Platform:
Windows 10
Git Bash shell

**Comment by prescottprue** [comment]
Interesting, thanks for reaching out. Auth works on a few of the apps I am testing with cypress-firebase, so maybe one of the setup steps was unclear or left out?

What names did you use for the values you set in cypress.env.json. Did you use createTestEnv to make the file or did you do it manually?

**Comment by ralphsmith80** [comment]
Thanks for responding! I'm with you. Everything appears to be okay. I spent a couple of days reviewing the docs to make sure it wasn't something obvious. 

This is what my relevant files look like (values omitted):

cypress.env.json
```
{
  "TEST_UID": "",
  "FIREBASE_PROJECT_ID": "",
  "FIREBASE_API_KEY": "",
  "FIREBASE_AUTH_JWT": ""
}
```
serviceAccount.json
```
{
  "type": "",
  "project_id": "",
  "private_key_id": "",
  "private_key": "",
  "client_email": "",
  "client_id": "",
  "auth_uri": "",
  "token_uri": "",
  "auth_provider_x509_cert_url": "",
  "client_x509_cert_url": ""
}
```

I used `createTestEnv` via `package.json` scripts to make the file but I did name them to my own liking.

package.json scripts
```
"e2e": "cypress run",
"e2e:open": "npm run e2e:testConfig && cypress open",
"e2e:testConfig": "cypress-firebase createTestEnvFile",
```

And I just use `npm run e2e:open` to generate the `cypress.env.json` file and run cypress locally.

**Note:** the docs show `"test:open": "npm run build:testConfig cypress open",` but I need the `&&` which would be typical. Possible typo?

**Comment by prescottprue** [comment]
Thanks for the info - Are you setting the `FIREBASE_AUTH_JWT` value yourself or are you having it set by `createTestEnvFile`?

[`firebase.auth().signInWithCustomToken` is called internally](https://github.com/prescottprue/cypress-firebase/blob/master/src%2FattachCustomCommands.js) with this value, and it seems like this error is called if it is not a valid custom Firebase token. I see that you noted that it is a valid JWT, and I am assuming that is the one generated by `createTestEnvFile`? Since that [internally calls, `admin.auth().createCustomToken`](https://github.com/prescottprue/cypress-firebase/blob/master/src%2FcreateTestEnvFile.js) it should be valid - maybe we are passing it some invalid info or something?

Is there a way you can provide the repo for me to reproduce this in? We can communicate over DMs on gitter if you want to keep it private. I am not able to replicate in the examples, and want to see if it is maybe something the specific project or the JWT that is generated.

**Comment by ralphsmith80** [comment]
I'm letting `createTestEnvFile` set the `FIREBASE_AUTH_JWT` value.

In an attempt to pair this down to a minimal use case I created a simple test script. I'm pulling values directly from the files noted in the setup. This test is successful.

If you're around tomorrow evening and we're still stumped I'll ping you on gitter.

```
const path = require('path')
const fs = require('fs')
const admin = require('firebase-admin')
const firebase = require('firebase')

function readJsonFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return {}
  }

  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'))
  } catch (err) {
    error(`Unable to parse ${filePath} - JSON is most likely not valid`)
    return {}
  }
}

const serviceAccount = readJsonFile(path.join('./serviceAccount.json'))
const envConfig = readJsonFile(path.join('./cypress.env.json'))
const { FIREBASE_PROJECT_ID, FIREBASE_API_KEY, TEST_UID } = envConfig

const appFromSA = admin.initializeApp(
  {
    credential: admin.credential.cert(serviceAccount),
    databaseURL: `https://${FIREBASE_PROJECT_ID}.firebaseio.com`
  },
  'withServiceAccount'
)

// set developer claims as { isTesting: true }
const defaultDeveloperClaims = { isTesting: true }

// Create auth token
const createToken = () =>
  appFromSA
    .auth()
    .createCustomToken(TEST_UID, defaultDeveloperClaims)
    .then(
      customToken => {
        console.log(`Custom token generated successfully`)
        // Remove firebase app
        appFromSA.delete()
        return customToken
      },
      e => console.log('failed to create token:', e)
    )

const signIn = token =>
  new Promise((resolve, reject) => {
    firebase.initializeApp({
      apiKey: FIREBASE_API_KEY,
      projectId: FIREBASE_PROJECT_ID
    })
    firebase.auth().onAuthStateChanged(auth => {
      if (auth) {
        resolve(auth)
      }
    })
    firebase
      .auth()
      .signInWithCustomToken(token)
      .catch(reject)
  })

createToken()
  .then(FIREBASE_AUTH_JWT => {
    console.log('sign in with token')
    return signIn(FIREBASE_AUTH_JWT)
  })
  .then(() => console.log('success'), e => console.log('fail', e))
```

**Comment by prescottprue** [comment]
Glad something worked! That is interesting that the test script worked - would love to get to the bottom of this one :)

**Comment by ralphsmith80** [comment]
Answers:
1. When you say `signIn` I'm just using the logic from above for testing. My app uses Google, Facebook, and email provided by firebase
1. It's does not have `firebase-` it is `keepify-dev`
1. I have a number of projects defined in `.firebaserc` but the `default` is the one I'm looking for
1. I tried to compare against the examples but the test logic I had was nil and I'm only using firebase authentication so it should be pretty straight forward

## Success

I started working today. I can't explain why but this was the order of operations.

1. In my previous comment I provided a test script I was using to validate token creating and authentication. Which worked successfully. 
1. Today I added another test to only validate the authentication with the `FIREBASE_AUTH_JWT ` token created from `createTestEnvFile`. I had an old token in that file from before. The test failed. 
1. I re-ran `cypress-firebase createTestEnvFile` to generate a new token and re-ran the test and it worked successfully.
1. I ran my cypress test sweet and it worked successfully.


For the record when this was failing I re-generated that token multiple times and verified the token was actually changing but I always received the `invalid token` error. I'm not sure why it started working but it is. 

As a random thought - I noticed my Windows OS (10) time was wrong today and I had to dig into the settings pretty deep to ensure it was set to update automatically via the internet. Maybe that was the issue and/or maybe I have a computer virus now. 🤷‍♂ 

**signInOnly test script:**
```
const { FIREBASE_AUTH_JWT } = readJsonFile(path.join('./cypress.env.json'))
const signInOnly = () =>
  signIn(FIREBASE_AUTH_JWT)
    .then(
      () => {
        console.log('sign in success')
        return firebase.auth().signOut()
      },
      e => console.log('sign in fail', e)
    )
    .then(
      () => console.log('sign out success'),
      e => console.log('sign out fail', e)
    )
```

**Comment by prescottprue** [comment]
Awesome to hear, thanks for the update! I always regenerate the token before running tests since I believe they are also invalid after an hour. You clock being wrong could have potentially played a roll, guess we will never know!

**Comment by JDansercoer** [comment]
I am terribly sorry. Seems I should have gone to bed last night instead of the late night coding session.

I never added the `fbConfig` in `commands.js`.

My apologies, and thanks for this great library!
