### ISSUE TITLE
Receiving Firebase Permission Errors (in my app) when I use call initializeApp in cypress

### ISSUE THREAD

**Issue by dhair-seva** [prescottprue/cypress-firebase#55]
I have been receiving "Permission Denied" errors when I add cypress with the following code:
```
const fbInstance = firebase.initializeApp(CypressConfig.firebase)

if (fbInstance) {
  (window as any).fbInstance = fbInstance
}
```

Here is the full `support/index.ts` file:
```
import * as firebase from "firebase/app"
import "firebase/auth"
import "firebase/database"
import "firebase/firestore"
import attachCustomCommands from "cypress-firebase/lib/attachCustomCommands"

import { CypressConfig } from "../models/config"

const fbInstance = firebase.initializeApp(CypressConfig.firebase)

if (fbInstance) {
  (window as any).fbInstance = fbInstance
}

attachCustomCommands({ Cypress, cy, firebase })

import "./login.command"
```
If I remove the initializeApp, my registration page passes without these errors. But if its in there, then it will fail with over 4-5 permission errors.
Keep in mind that I'm using:
- Angular 8+
- "cypress-firebase": "0.3.0-alpha" (for typescript support)
- "typescript": "3.5.3"
- "firebase": "6.6.0"
- "firebase-admin": "8.5.0"
- "firebase-functions": "3.2.0"

Before submitting this, I wanted to explain what **I think it is**. Perhaps its because I'm using the same firebase config that I use in my app? Would that be the reason? If not, then I feel its some bug. But I imagine this would have came up in someone else's app. **Thoughts?**

**Comment by prescottprue** [comment]
In the examples there is code [to check the window for a Firebase instance, and only initialize if that isn't in place](https://github.com/prescottprue/cypress-firebase/blob/master/examples/react-redux-firebase/src/store.js#L11-L19). Have you given something like that a try?

I thought that was already in the setup instructions, but doesn't appear to be, so I'll update that.

**Comment by dhair-seva** [comment]
Thanks for that information. So your saying it should be like this?
```
import * as firebase from "firebase/app"
import "firebase/auth"
import "firebase/database"
import "firebase/firestore"
import attachCustomCommands from "cypress-firebase/lib/attachCustomCommands"

import { CypressConfig } from "../models/config"

if (!(window as any).fbInstance) {
  // Initialize Firebase instance
  firebase.initializeApp(CypressConfig.firebase)
}

attachCustomCommands({ Cypress, cy, firebase })

import "./login.command"
```

Yeah, I will try to make that example. That would be nice to have that example. Once I get some time, I will do that!

**Comment by dhair-seva** [comment]
This worked! At least, from what I can tell. Thank you!

**Comment by dhair-seva** [comment]
I decided to begin adding the Angular example to this repo. However, I was wondering if you could send me the fbConfig? I would like them to be in your list of projects so its all in one place. Just like you have in the other places like so:
![image](https://user-images.githubusercontent.com/51764839/65017200-5a8ee200-d8e3-11e9-86c8-92eafd851106.png)

**Comment by dhair-seva** [comment]
I have a branch (from my fork of your repo). Its not complete, as I haven't done tests, and this is really just copying my logic over, but if you had time to chip in (and add the firebase config and such), there it is!

https://github.com/dhair-seva/cypress-firebase/tree/feature/dmh/angular-example

**Comment by dhair-seva** [comment]
In a day or so, I will have a branch open to look at. Currently, I have a few things to do, before I can do that.
