### ISSUE TITLE
Changed location of config.json

### ISSUE THREAD

**Issue by dan-hirst** [prescottprue/cypress-firebase#6]
Hi,

In 0.0.8 I set my TEST_UID in config.json which I stored in $PROJECT_ROOT/cypress/config.json.

In 0.1.0 the library appears to be looking for the config file in $PROJECT_ROOT/config.json.

I think you can see this in the new file filepaths.js that sets the location https://github.com/prescottprue/cypress-firebase/blob/d7a84394181866d19b845ed3efa1051e0465e02d/src/filePaths.js#L22

I think this is unintentional because a new section of the docs describes setting the config directory by using a new integrationFolder property in cypress.json
https://github.com/prescottprue/cypress-firebase/blob/master/README.md#folders

What do you think? If you want me to then I'm happy to open a PR either way. (Either to update the file locations to use the integrationsFolder property or to update the README)

Also happy to hear if the issue is a misconfiguration on my part!

Thanks for the library!

**Comment by prescottprue** [comment]
Thanks for reporting. It is most likley due to how the support for loading config from `cypress.json` (maybe if it isn't there is causes an issue?). Feel free to open a PR, glad that someone is using the new version already!

**Comment by hoop71** [comment]
@dan-hirst @prescottprue I think it needs to be inside of the cypress folder if possible. `config.json` is too generic of a name to live at the project root and will no doubt conflict with existing files in many repos.

**Comment by prescottprue** [comment]
Switched the fallback back to being within `cypress` (removing that was not intentional) and released the change as in [`v0.1.1` release](https://github.com/prescottprue/cypress-firebase/releases/tag/v0.1.1). Thanks for reaching out.

**Comment by dan-hirst** [comment]
Thanks! 👍
