### ISSUE TITLE
Can't use Firestore Emulator

### ISSUE THREAD

**Issue by Alvadda** [prescottprue/cypress-firebase#609]
I can't figure out how to set cypress-firebase up to use my local Firestore Emulator. It seems that it used my local Auth from the Emulator, but  not my Firestore .

In my cypress command.ts, I configured it like it the docs described:
```ts
const fbConfig = {
 //my config here
}

firebase.initializeApp(fbConfig)

firebase.firestore().settings({
  host: 'http://localhost:5051/',
  ssl: false,
})

// or 
firebase.firestore().useEmulator('localhost', 5051)

firebase.auth().useEmulator('http://localhost:9099/')

attachCustomCommands({ Cypress, cy, firebase })
```

but when i call 
`cy.callFirestore('get', 'users').then((user) => {
      console.log(user)
    })`

I always get the data from my production Firestore not from my Emulator...

Auth seems fine, I get this message from Firebase: 
`You are using the Auth Emulator, which is intended for local testing only.  Do not use with production credentials`

My firebase.json looks like this: 

```js
  "emulators": {
    "auth": {
      "port": 9099
    },
    "firestore": {
      "port": 5051
    },
    "ui": {
      "enabled": true
    }
  }
```

I don't know what I'm doing wrong and can't find any solutions, as it seems it should work like that above!

If anyone has the same problem or a solution, I would appreciate it.

**Comment by pascalbe-dev** [comment]
How did you solve the problem? 
I have a similar one. It writes to the production database although I really do not know, where it pulls the information about it from (I changed the firebase config).

**Comment by OneFourFree** [comment]
cross-env FIRESTORE_EMULATOR_HOST="localhost:8080" cypress open
