### ISSUE TITLE
Node 12 and NODE_TLS_REJECT_UNAUTHORIZED problem

### ISSUE THREAD

**Issue by bartlomiejborzucki** [prescottprue/cypress-firebase#65]
I checked cypress-firebase 0.4.0 with node 10 and node 12 and IMHO your application has a problem with node 12. I got this error 

> NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

![error_cypress-firebase](https://user-images.githubusercontent.com/2742766/68338913-ce7b8880-00e3-11ea-9374-b5fc5a9e5349.png)

in my application when I used only node 12. When I used node 10 everything was perfect

My all dependencies (I checked cypress: 3.4.1/3.5.0/3.6.0): 

> "dependencies": {
>     "@angular/animations": "^8.0.0",
>     "@angular/cdk": "~8.0.2",
>     "@angular/common": "^8.0.0",
>     "@angular/compiler": "^8.0.0",
>     "@angular/core": "^8.0.0",
>     "@angular/fire": "^5.2.1",
>     "@angular/flex-layout": "^8.0.0-beta.27",
>     "@angular/forms": "^8.0.0",
>     "@angular/material": "~8.0.2",
>     "@angular/platform-browser": "^8.0.0",
>     "@angular/platform-browser-dynamic": "^8.0.0",
>     "@angular/pwa": "^0.13.8",
>     "@angular/router": "^8.0.0",
>     "@angular/service-worker": "^8.0.0",
>     "@auth0/angular-jwt": "^2.1.0",
>     "@fortawesome/angular-fontawesome": "^0.4.0",
>     "@fortawesome/fontawesome-free": "^5.8.1",
>     "@fortawesome/fontawesome-svg-core": "^1.2.19",
>     "@fortawesome/free-regular-svg-icons": "^5.9.0",
>     "@fortawesome/free-solid-svg-icons": "^5.9.0",
>     "@ngrx/effects": "^8.0.1",
>     "@ngrx/entity": "^8.0.1",
>     "@ngrx/router-store": "^8.0.1",
>     "@ngrx/store": "^8.0.1",
>     "@ngrx/store-devtools": "^8.0.1",
>     "@nrwl/angular": "8.7.0",
>     "angular-in-memory-web-api": "0.8.0",
>     "chart.js": "^2.8.0",
>     "core-js": "^2.5.4",
>     "date-fns": "^2.0.1",
>     "date-fns-timezone": "^0.1.4",
>     "firebase": "^6.3.1",
>     "firebase-admin": "^8.3.0",
>     "firebase-functions": "^3.2.0",
>     "hammerjs": "^2.0.8",
>     "jq": "^1.7.2",
>     "lodash": ">=4.17.11",
>     "logrocket": "^0.6.20",
>     "logrocket-ngrx": "^0.1.1",
>     "ng2-charts": "^1.5.0",
>     "ngx-sortablejs": "^3.1.3",
>     "primeng": "^8.0.1",
>     "quill": "^1.3.6",
>     "rxjs": "^6.5.2",
>     "sortablejs": "^1.9.0",
>     "truncate-html": "^1.0.2",
>     "tsify": "^4.0.1",
>     "uuid": "^3.3.3",
>     "zone.js": "^0.9.1"
>   },
>   "devDependencies": {
>     "@angular-devkit/build-angular": "^0.803.3",
>     "@angular/cli": "8.3.15",
>     "@angular/compiler-cli": "^8.0.0",
>     "@angular/language-service": "^8.0.0",
>     "@ngrx/schematics": "^8.0.1",
>     "@nrwl/cypress": "8.7.0",
>     "@nrwl/jest": "8.7.0",
>     "@nrwl/node": "8.7.0",
>     "@nrwl/workspace": "8.7.0",
>     "@types/faker": "^4.1.4",
>     "@types/jest": "24.0.9",
>     "@types/node": "~8.9.4",
>     "codelyzer": "~5.0.1",
>     "concurrently": "^4.1.2",
>     "cypress": "^3.6.0",
>     "cypress-firebase": "^0.4.0",
>     "cypress-pipe": "^1.5.0",
>     "dotenv": "6.2.0",
>     "eslint": "6.1.0",
>     "faker": "^4.1.0",
>     "firebase-functions-test": "^0.1.6",
>     "firebase-tools": "^6.10.0",
>     "git-describe": "^4.0.4",
>     "husky": "^1.3.1",
>     "jest": "24.9.0",
>     "jest-preset-angular": "7.0.0",
>     "ng-mocks": "8.0.0",
>     "prettier": "1.16.4",
>     "rxjs-tslint-rules": "^4.14.3",
>     "ts-jest": "24.0.0",
>     "ts-node": "~7.0.0",
>     "tslint": "~5.11.0",
>     "typescript": "~3.5.3"
>   }
> 
> 

Do you have the same problem? Could you fix it?

**Comment by prescottprue** [comment]
I have not experienced this, but most often am running node 10. Have you tried doing what the error says and setting the environment variable:

```
process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;
```

I'll look into if this should be added as part of the code for newer node versions. Not sure, but it seems like node is trying to make an https request but there is not the write certificate [as mentioned in this stackoverflow post](https://stackoverflow.com/questions/35633829/node-js-error-process-env-node-tls-reject-unauthorized-what-does-this-mean)

**Comment by bartlomiejborzucki** [comment]
Hi, 
thanks for the answer. I used the angular-dev server and this specific command: cy.callFirestore.  

In the beginning, I thought that it is a cypress problem so I found this issue: https://github.com/cypress-io/cypress/pull/5256/files and upgraded the cypress version to 3.5 and later to 3.6, but this error didn't disappear. 

I didn't try this: process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0; but I tried this: 
# export NODE_TLS_REJECT_UNAUTHORIZED=0 && npm run e2e 
and it didn't help as well.

**Comment by prescottprue** [comment]
Are you sure [that the fix mentioned in that issue](https://github.com/cypress-io/cypress/pull/5256/files) was included in v3.6 of cypress? I don't see it listed anywhere in the [release notes](https://github.com/cypress-io/cypress/releases), but it is weird because I do see it in [the master branch](https://github.com/cypress-io/cypress/blob/master/packages/server/index.js#L25). I'm going to look into replicating to see if there is maybe some environment not being passed into scripts being called in exec

**Comment by bartlomiejborzucki** [comment]
I'm not sure but I found this: https://github.com/cypress-io/cypress/issues/5248 
This path was added to Cypress 3.5.

**Comment by prescottprue** [comment]
Closing this since it is similar to #13 - updates for this issue will be made there. Thanks for reporting
