### ISSUE TITLE
No such file or directory when invoking callRtdb

### ISSUE THREAD

**Issue by r1ckhenry** [prescottprue/cypress-firebase#66]
Hi,

I'm running into an error when I call the callRtdb function. I've setup cypress firebase with create-react-app as per the instructions in the examples. However, when I run the following test:

```
describe("first test", () => {
  it("works", () => {
    cy.login();
    cy.callRtdb("remove", `managers/${Cypress.env("TEST_UID")}`)
    cy.visit("/");
  });
});
```
I get the following error:

```
CypressError: cy.exec('$(npm bin)/firebase database:remove /managers/xxxx -P firebase-app-id -y') failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 127

Stderr:
zsh:1: no such file or directory: /Users/Richard/Code/premier-manager/node_modules/.bin/firebase
```
First of all, I tried to pass in the ` {failOnNonZeroExit: false}` with no difference in the error. I've since focussed on the `Stderr:`. I can see firebase is a node module however there is no `firebase` file in the `.bin` directory. Does this need to be generated?

Any help would be appreciated!

**Comment by prescottprue** [comment]
Do you have firebase-tools installed? That is what is needed for `firebase` to be available by CLI and for it to add a file to the bin - [it is listed as a peer dependency for this reason](https://github.com/prescottprue/cypress-firebase/blob/master/package.json#L27).

**Comment by r1ckhenry** [comment]
Thanks so much, I knew it would be something like that! Works perfectly!
