### ISSUE TITLE
'$' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by dhair-seva** [prescottprue/cypress-firebase#68]
When starting to use the cy.callFirestore command, I received this error:

![image](https://user-images.githubusercontent.com/51764839/69109644-9b1af100-0a35-11ea-80d3-6ab37161a485.png)

Do I need to install something for it to recognize the $(npm bin) syntax? Actually, I just realized that this could be because I'm using yarn. Any thoughts on this?

**Comment by prescottprue** [comment]
Hmm... Yarn shouldn't impact the npm bin.

Do you have firebase-tools installed within your project? It is a peer-dependency as it is needed to run commands with admin privileges.

I haven't really seen this before, and not sure why it wouldn't be parsing that as expected. In the past `npx` was used, so I may look into switching back to that instead of a command containing the bin reference.

Just so I can try replicating - which version of cypress, cypress-firebase, and firebase-tools are you using?

**Comment by dhair-seva** [comment]
Thanks for your speedy reply.

I have firebase-tools installed:
**firebase-tools**: 7.8.0
**cypress**: 3.4.1
**cypress-firebase**: 0.4.1

**Comment by dhair-seva** [comment]
I haven't tried get. I have tried set and delete commands. I will try get and let you know.

**Comment by dhair-seva** [comment]
Hmm, I'm not sure what I did, but now this is the error I am getting. This is for get, set, and delete commands:
```
CypressError: cy.exec('$(npm bin)/firebase-extra firestore get companies/DevAutomation/projects/DevAutomationProject/Test Cases/1') failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
' is not recognized as an internal or external command,
operable program or batch file.

Because this error occurred during a 'before all' hook we are skipping the remaining tests in the current suite: 'Client New Test Page'
```

**Comment by prescottprue** [comment]
It looks like your file path has a space in it - could you try escaping it by putting a `\` in front of that?

cypress-firebase should definitely handle this case internally, but just want to see if that helps

**Comment by dhair-seva** [comment]
Good idea! I tried to do the `\` just now, but same error. I also tried changing the space to `%20` (which is what we had to do for firebase rules (to be honest, I wish we could change this, but this is in production code, so I need that. However, it seems that it cannot find the command. I ran this same command in the command line, except changed $(npm bin) to ./node_modules/.bin, and it ran the command just fine. Its only when I run it in cypress that it fails.

**Comment by prescottprue** [comment]
That is very intesting, not sure why I haven't experienced this. What type of machine are you using to run Cypress? Windows, mac, or linux?

Looks like we may have to switch things back to `npx` instead of using `$(npm bin)`, so I'll look into making that change

**Comment by dhair-seva** [comment]
I'm on Windows 10. Thanks for your help! I really like this module.

**Comment by dhair-seva** [comment]
I changed this in constants.js on my end:
```
exports.FIREBASE_TOOLS_BASE_COMMAND = 'node_modules\\.bin\\firebase';
// Path to firebase-tools-extra Command Line tool (wrapper for firebase-tools)
exports.FIREBASE_EXTRA_PATH = 'node_modules\\.bin\\firebase-extra';
```
And it worked. However, I'm getting this error, but I don't think its related
```
Error: the string "(node:18408) UnhandledPromiseRejectionWarning: Error: Fixture not found at path: test\\e2e\\fixtures\\'{_id:Automation-Test-Case-1574356128828 ... }
```
I thought that the set command could have an object passed in (I have a function to generate my object to set the value to). Am I using it right? I'm asking in this since I'm making sure this change fixes it.

**Comment by prescottprue** [comment]
@dhair-seva Glad to hear switching it up worked. For passing in a fixture, you will want to have an object, but it seems like you might have passed a string since it thinks it is a fixture path?

Did you try switching them to using `npx` like `npx firebase-extra` ? I think that might be the best path forward since it will handle local and global versions

**Comment by dhair-seva** [comment]
@prescottprue  I haven't tried npx. I will when I get a chance. I passed in an object. This is what I used:
```
const testCase = generateTestCase()

  before(() => {
    cy.wrap(Config)
    cy.wrap(Cypress.env())
    cy.tokenLoginAs("admin")
    cy.log("Creating test case...")
      .callFirestore("set", getTestCaseDocPath("admin", testCase._id), testCase)
      .log("Test Case created.")

  })
```
generateTestCase returns an object like:
{ _id: 'my-custom-id', ... }

**Comment by dhair-seva** [comment]
I found a workaround, and this way works -- 
```
cy.tokenLoginAs("admin")
      .log("Creating test case...")
      .writeFile(testCaseFixturePath, testCase)
      .then(() => {
        cy.callFirestore("set", getTestCaseDocPath("admin", testCase._id), testCaseFixtureName)
        .as("testCaseCreated")
        .log("Test Case created.")
      })
```
Then in after(), I delete the file and the database item.

So I know that this error is simply because of the path.

Also, I have now tried npx, and that works great for me.
