### ISSUE TITLE
bug(docs): unclear explanation of project id + creds loading

### ISSUE THREAD

**Issue by pedrocarloto** [prescottprue/cypress-firebase#700]
**Describe the bug**

I am doing this in a clean installation of cypress V10.1.0 and cypress-firebase V2.2.1.

I have went through all the steps described on the readme file to execute a simple test on firestore, but unfortunatelly I keep getting the error:
> cy.task('callFirestore') failed with the following error:
>  Unable to detect a Project Id in the current environment.

 I am trying to reach my own firebase project.
(First screenshot)

The same is true if I try to execute the example code provided in cypress-firebase, but I get a slight different error:
> cy.task('callFirestore') failed with the following error:
> Could not load the default credentials.

(Second screenshot)

**To Reproduce**

Main problem:
Implement the code described on the Readme file in section "Setup"
Connect it to your won firebase project with your credentials.

Secondary problem
1. On the cypress-firebase code
2. go to examples/basic
3. run: yarn test:open
4. run Firestore tests

**Expected behavior/code**
The test would execute and pass.

**Additional Context/Screenshots**

First:
![image](https://user-images.githubusercontent.com/1236277/174816957-c6bd8efe-5862-4c3a-b501-5a427b814b30.png)

Second:
![image](https://user-images.githubusercontent.com/1236277/174817783-c15034c0-50e1-42af-959e-20e68777230e.png)

**Comment by pedrocarloto** [comment]
@prescottprue, in theory I don't need a serviceAccount.json to be able to connect to firestore, correct? In the readme file that's not clear. (I will make some suggestions to the Readme file with a PR when I get this to work :) )

Anyway I tried adding a serviceAccount.json to my root folder and I still get the same error.
Thank you.

**Comment by andershoegh** [comment]
> 

Could you provide the cypress.config.ts/js from your project?

**Comment by andershoegh** [comment]
What worked for me was setting a project ID when registering the node events like so:

`cypressFirebasePlugin(on, config, admin, {
        projectId: "PROJECT_ID_FROM_CONFIG",
      });`

**Comment by pedrocarloto** [comment]
Oh, nice! It also worked for me. I am now getting another error:

> Could not load the default credentials.

![image](https://user-images.githubusercontent.com/1236277/175346785-63988551-f464-43d0-b6c1-265c5f0517ea.png)

I will try to mess around and see if I can get pass through this auth problem.

Anyway I feel there is a problem with the package, since using the override you suggest should be optional, no?

**Comment by prescottprue** [comment]
@pedrocarloto I would agree that this is still an issue that there is not clear messaging from the lib or documentation about it. Default credentials should be automatically used if they are available (i.e. `GOOGLE_APPLICATION_CREDENTIALS` environment variable points to the path instead of you requiring directly like you did) - or if in Github actions than the gcloud steps export default credentials

**Comment by AurelienLoyer** [comment]
> What worked for me was setting a project ID when registering the node events like so:
> 
> `cypressFirebasePlugin(on, config, admin, { projectId: "PROJECT_ID_FROM_CONFIG", });`

FYI this solve my (not working `cy.callFirestore('update')`) issue https://github.com/prescottprue/cypress-firebase/issues/345#issuecomment-1284632330 🙏
