### ISSUE TITLE
README setup causes error

### ISSUE THREAD

**Issue by YMRTZ** [prescottprue/cypress-firebase#711]
**Describe the bug**

Setup method in README causes Cypress to break

**To Reproduce**
1. Follow the steps listed in the README to install Cypress and cypress-firebase

**Expected behavior/code**
Cypress should run properly after following setup steps.

**Possible Solution**

Replacing "supportFile: 'cypress/support/e2e/index.js'," inside cypress.config.ts with "supportFile: 'cypress/support/e2e.ts',", which corresponds to the support commands file, solved the issue.

**Comment by prescottprue** [comment]
Good callout - removing since the default location is used and therefore does not need to be specified
