### ISSUE TITLE
bug(docs): README.md setup is not clear about service account

### ISSUE THREAD

**Issue by Tockra** [prescottprue/cypress-firebase#715]
Hi,

if you follow the readme.md you run into multiple problems.

After step 1 and step 2 I ran into the problem that there is no `supportFile: 'cypress/support/e2e/index.js'` the readme let me create a `cypress/support/e2e.ts`. After changing this line in `cypress.config.ts` it works.

Step 3 doesn't work. I got the error message:
```bash
CypressError
cy.task('callFirestore') failed with the following error:

> Unable to detect a Project Id in the current environment.
To learn more about authentication and Google APIs, visit:
https://cloud.google.com/docs/authentication/getting-started[Learn more](https://on.cypress.io/api/task)
```

I guess I need to set a service account in the serviceAccount.json. But this isn't documented well anywhere (and not before step 3). I have no idea what content I have to add there and where I get my service account json. 
Section https://github.com/prescottprue/cypress-firebase#considerations-for-ci bringt randomly this service account into the readme and doesn't describe how to get it, where to place it, ...

Maybe somebody could help me here.

T

**Comment by Tockra** [comment]
Okay I found the information that I can create the service account at firebase console (console.firebase.google.com) via `settings -> project settings -> service accounts`.
But maybe you should add this somewhere.

**Comment by Dale-777** [comment]
@Tockra I'm stuck on the exact same issue, did you take the generated .json file from "generate private key" via settings -> project settings -> service accounts

and save this as the env variable named SERVICE_ACCOUNT? or did you place that in the file named serviceAccount.json? and if so where did you place or make any reference to that file

Thanks for your help

**Comment by Tockra** [comment]
I saved it as serviceAccount.json in the project folder.
Further I set this file nowhere. It automatically worked

**Comment by prescottprue** [comment]
Thanks for calling out that this is unclear in the docs - I'll make sure to update the steps.

Wanted to clarify on the error messaging though: providing GCLOUD_PROJECT environment variable should be enough for callFirestore to talk to the emulators (hence the not able to determine project message). The service account is needed for calls to full hosted RTDB/Firestore instances (not emulated) or for generating custom auth tokens
