### ISSUE TITLE
bug(firestore): FieldValue.delete() not handled correctly

### ISSUE THREAD

**Issue by mcarriere** [prescottprue/cypress-firebase#723]
**Describe the bug**
When we try to delete a field during a FIrestore document update, instead of the field getting deleted it seems to store the function as a value.

**To Reproduce**

```
cy.callFirestore(‘update’, ‘my-collection/doc-id’, { drawn: firebase.firestore.FieldValue.delete() });
```

We tried with Firebase compat and the new Firebase 9 syntax.

**Expected behavior/code**
The drawn field getting deleted

**Additional Context/Screenshots**
![image](https://user-images.githubusercontent.com/25467653/204581152-d4bdfed7-dc5d-41dd-b1be-fd495f6da394.png)

**Comment by prescottprue** [comment]
Thanks for reporting - I'm wondering if this is getting picked up by the timestamp handling logic. Either way this should be supported, even with nested fields
