### ISSUE TITLE
Promise issue on cy.logout

### ISSUE THREAD

**Issue by dArignac** [prescottprue/cypress-firebase#9]
Hi there,

first, thanks for the project, it helped me a lot!

Unfortunately I have an issue when using `cy.logout`.

I have tests with `cy.login()` in the Cypress `before` hook, those work great.
But I also want to test the logged out state, so I defined `cy.logout()` in the `before` hook accordingly. Those tests fail on the `cy.logout()` command with the following:

```
Error:    CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

The command that returned the promise was:

  > cy.logout()

The cy command you invoked inside the promise was:

  > cy.log()

Because Cypress commands are already promise-like, you don't need to wrap them or return your own promise.

Cypress will resolve your command with whatever the final Cypress command yields.

The reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.

https://on.cypress.io/returning-promise-and-commands-in-another-command

Because this error occurred during a 'before all' hook we are skipping the remaining tests in the current suite: 'Landing Page Unauthenticated'
```

I'm not sure if this is an issue on my side (wrong usage,...) or something of the lib.
For reference you can find the code of the failing test [here](https://github.com/dArignac/treasury/blob/0150c57c07f81ac8cac8c1412761337ab4eba840/treasury/cypress/integration/home.noauth.spec.js).

Thanks for your help!
-Alex

**Comment by prescottprue** [comment]
Fix released in [`v0.1.1` release](https://github.com/prescottprue/cypress-firebase/releases/tag/v0.1.1), thanks for reporting and let me know if it doesn't work as expected.

**Comment by dArignac** [comment]
Hi Scott, thank you for the fast fix, it works now as expected.

**Comment by othondev** [comment]
Hi, 
I am detecting the same error issue but it is intermittent.

Version: 2.2.1

Log:
  2) Login and Logout flow
       "after each" hook for "Enter with inactive parent email and password":
     CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

The command that returned the promise was:

  > `cy.logout()`

The cy command you invoked inside the promise was:

  > `cy.wait()`

**Comment by prescottprue** [comment]
@othondev Can you create a new issue with code to reproduce? There isn't a usage of `cy.wait` in the lib that I'm aware of. [here is the logic for logout](https://github.com/prescottprue/cypress-firebase/blob/main/src/attachCustomCommands.ts#L392-L397) - a promise is returned, but there isn't any command invoked inside of it
