### ISSUE TITLE
Support for monorepos/yarn worksapces

### ISSUE THREAD

**Issue by tad3j** [prescottprue/cypress-firebase#94]
I wanted to use this package but unfortunately I can't get it working with lerna monorepo / yarn workspaces.

Problem is that I have `.firebaserc` file stored in `root` of my project (so it's available to web, mobile and functions project files), but my web application lives in `packages/web`. 

It doesn't matter if I run cyrpess from packages/web folder (via `cypress open`) or from root folder (via `cypress open --project packages/web`), command always fails with exception:

Here is the exception being thrown:

> We invoked the function exported by packages\web\cypress\plugins\index.js, but it threw an error.
> 
> Error: .firebaserc file not found
>     at loadFirebaseRc (node_modules\cypress-firebase\lib\extendWithFirebaseConfig.js:15:15)
>     at getFirebaseProjectIdFromConfig (node_modules\cypress-firebase\lib\extendWithFirebaseConfig.js:42:28)
>     at extendWithFirebaseConfig (node_modules\cypress-firebase\lib\extendWithFirebaseConfig.js:74:31)
>     at module.exports (packages\web\cypress\plugins\index.js:23:10)
>     at Local\Cypress\Cache\4.0.2\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:77:1

**Comment by prescottprue** [comment]
@tad3j Thanks for reporting - I'll look into this

**Comment by prescottprue** [comment]
@tad3j Have you tried any of the versions on the `next` tag? The v1.0.0 version series does not use `.firebaserc` for any config anymore, so hopefully that should work as you expect.

**Comment by prescottprue** [comment]
v1.0.0 has been released to latest and it no longer uses .firebaserc. Going to close for now, please let me know if you are still experiencing an issue and we can reopen
